#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd "$(git rev-parse --show-toplevel)" || exit 1

FAILED=0

echo "Running all frontend tests..."
npm --prefix frontend test || FAILED=1

echo "Running all backend tests..."
(cd backend && bundle exec rspec) || FAILED=1

if [ $FAILED -eq 1 ]; then
  echo >&2 "\n❌ ERROR: Push aborted due to failing tests.\n"
  exit 1
fi

exit 0
